name: build documentation ⚙️

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
  pull_request:
    branches:
      - main
    paths:
      - 'docs/**'

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      name: setup Python
      with:
        python-version: "3.10"
    - name: build docs ⚙️
      uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"